server.port=8081
spring.thymeleaf.cache=false
# Path to firebase service account json file
firebase.config-path=classpath:serviceAccountKey.json

# T?ng gi?i h?n upload file lên 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
