server.port=8081
spring.thymeleaf.cache=false
# Path to firebase service account json file
firebase.config-path=classpath:serviceAccountKey.json

# T?ng gi?i h?n upload file lên 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# C?u hình Mail Server (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhminh778894@gmail.com
spring.mail.password=ycks grup khbb kbyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
